apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.widgetbridge'
version = '1.0.0'

android {
  namespace 'expo.modules.widgetbridge'
  compileSdk 36

  defaultConfig {
    minSdk 24
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = '17'
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}"
}
