const fs = require('fs');
const path = require('path');
const {
  withAndroidManifest,
  withDangerousMod,
  withAppBuildGradle,
  AndroidConfig,
} = require('expo/config-plugins');

/**
 * Adds the Glance app widgets to the generated Android project.
 *
 * `android/` is regenerated by prebuild, so the Kotlin sources, the provider
 * descriptors and the manifest receivers can't live there — they'd be wiped.
 * This plugin copies them in from targets/android-widgets on every prebuild.
 * (@bacons/apple-targets does the equivalent job on iOS; it has no Android side.)
 */

const SOURCE_DIR = 'targets/android-widgets';
const PACKAGE = 'com.owaiskhan.monthlyplanning';

/** receiver class -> provider descriptor in res/xml */
const WIDGETS = [
  ['RadialReceiver', 'widget_radial'],
  ['YearReceiver', 'widget_year'],
  ['ProgressReceiver', 'widget_progress'],
  ['StreakReceiver', 'widget_streak'],
  ['TodayReceiver', 'widget_today'],
  ['GoalsReceiver', 'widget_goals'],
  ['QuoteReceiver', 'widget_quote'],
];

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dest);
    else fs.copyFileSync(src, dest);
  }
}

const withWidgetSources = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const root = cfg.modRequest.projectRoot;
      const androidMain = path.join(cfg.modRequest.platformProjectRoot, 'app/src/main');

      const kotlinFrom = path.join(root, SOURCE_DIR, 'kotlin');
      const kotlinTo = path.join(androidMain, 'java', ...PACKAGE.split('.'), 'widgets');
      copyDir(kotlinFrom, kotlinTo);

      const resFrom = path.join(root, SOURCE_DIR, 'res');
      copyDir(resFrom, path.join(androidMain, 'res'));

      return cfg;
    },
  ]);

const withWidgetReceivers = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.receiver = (application.receiver ?? []).filter(
      (r) => !(r.$?.['android:name'] ?? '').startsWith(`${PACKAGE}.widgets.`)
    );

    for (const [receiver, info] of WIDGETS) {
      application.receiver.push({
        $: {
          'android:name': `${PACKAGE}.widgets.${receiver}`,
          'android:exported': 'true',
          'android:label': '@string/app_name',
        },
        'intent-filter': [
          { action: [{ $: { 'android:name': 'android.appwidget.action.APPWIDGET_UPDATE' } }] },
        ],
        'meta-data': [
          {
            $: {
              'android:name': 'android.appwidget.provider',
              'android:resource': `@xml/${info}`,
            },
          },
        ],
      });
    }
    return cfg;
  });

/**
 * Glance is Compose, so the app module needs the Compose compiler plugin. Expo's
 * template doesn't enable it (it gates Compose behind a `coreFeatures` flag that
 * only applies to Expo modules), so it's applied here.
 *
 * The version has to match the project's Kotlin. `expo-root-project` publishes
 * that as `rootProject.ext.kotlinVersion`, which is set by the time the app
 * module is evaluated.
 */
const withGlanceDependency = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes('androidx.glance:glance-appwidget')) return cfg;

    cfg.modResults.contents = cfg.modResults.contents.replace(
      /dependencies\s?{/,
      `dependencies {
    implementation "androidx.glance:glance-appwidget:1.1.1"`
    );

    const composeCompiler = `buildscript {
    repositories { mavenCentral() }
    dependencies {
        classpath("org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:\${rootProject.ext.kotlinVersion}")
    }
}
apply plugin: "org.jetbrains.kotlin.plugin.compose"

`;
    // a second android {} block merges with the first, which is far less
    // brittle than splicing into the existing one
    cfg.modResults.contents =
      composeCompiler +
      cfg.modResults.contents +
      `
android {
    buildFeatures {
        compose true
    }
}
`;
    return cfg;
  });

module.exports = (config) =>
  withGlanceDependency(withWidgetReceivers(withWidgetSources(config)));
